import { useState } from 'react';
import { Button, Card, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { AddRounded, DeleteOutlineRounded, EditRounded } from '@mui/icons-material';
import { useCategories, useCreateCategory, useDeleteCategory, useUpdateCategory } from '../../hooks/useBlogData';
import { listFrom } from '../../utils/apiData';
import { apiErrorMessage } from '../../api/axiosClient';
import { useToast } from '../../context/ToastContext';
import { CardSkeletons, StateCard } from '../../components/AsyncState';

const slugify = (value) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
export default function Categories() {
  const query = useCategories(); const create = useCreateCategory(); const update = useUpdateCategory(); const remove = useDeleteCategory(); const { showToast } = useToast();
  const [dialogOpen, setDialogOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState({ name: '', description: '' }); const [target, setTarget] = useState(null);
  const categories = listFrom(query.data, ['categories']);
  const openForm = (category) => { setEditing(category || null); setForm(category ? { name: category.name, description: category.description || '' } : { name: '', description: '' }); setDialogOpen(true); };
  const save = async () => { try { if (editing) await update.mutateAsync({ id: editing.id, values: form }); else await create.mutateAsync(form); showToast(`Category ${editing ? 'updated' : 'created'}.`); setDialogOpen(false); } catch (e) { showToast(apiErrorMessage(e), 'error'); } };
  const confirmDelete = async () => { try { await remove.mutateAsync(target.id); showToast('Category deleted.'); setTarget(null); } catch (e) { showToast(apiErrorMessage(e), 'error'); } };
  return <><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2} mb={4}><div><Typography variant="h3">Categories</Typography><Typography color="text.secondary">Organize posts into clear topics.</Typography></div><Button variant="contained" startIcon={<AddRounded />} onClick={() => openForm()}>New category</Button></Stack>
    {query.isLoading ? <CardSkeletons /> : query.isError ? <StateCard title="Categories could not be loaded" message={apiErrorMessage(query.error)} severity="error" /> : <Card><Table><TableHead><TableRow><TableCell>Name</TableCell><TableCell>Slug</TableCell><TableCell>Posts</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{categories.map((category) => { const count = category.postCount ?? category.postsCount ?? category._count?.posts ?? 0; return <TableRow key={category.id}><TableCell><Typography fontWeight={600}>{category.name}</Typography><Typography variant="caption" color="text.secondary">{category.description}</Typography></TableCell><TableCell>{category.slug}</TableCell><TableCell>{count}</TableCell><TableCell align="right"><IconButton onClick={() => openForm(category)}><EditRounded /></IconButton><IconButton color="error" onClick={() => setTarget(category)}><DeleteOutlineRounded /></IconButton></TableCell></TableRow>; })}</TableBody></Table></Card>}
    <Dialog open={dialogOpen} onClose={() => setDialogOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing ? 'Edit category' : 'New category'}</DialogTitle><DialogContent><Stack spacing={2} pt={1}><TextField label="Name" required autoFocus value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><TextField label="Description" multiline minRows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><Typography variant="body2" color="text.secondary">Slug preview: /category/{slugify(form.name) || 'category-name'}</Typography></Stack></DialogContent><DialogActions><Button onClick={() => setDialogOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={!form.name.trim() || create.isPending || update.isPending}>Save</Button></DialogActions></Dialog>
    <Dialog open={Boolean(target)} onClose={() => setTarget(null)}><DialogTitle>Delete category?</DialogTitle><DialogContent>{(target?.postCount ?? target?.postsCount ?? target?._count?.posts ?? 0) > 0 ? 'This category still has posts. The API will block deletion until they are reassigned.' : `Delete “${target?.name}”?`}</DialogContent><DialogActions><Button onClick={() => setTarget(null)}>Cancel</Button><Button color="error" variant="contained" onClick={confirmDelete}>Delete</Button></DialogActions></Dialog></>;
}
